### ISSUE TITLE
TypeError: object of type 'int' has no len()

### ISSUE THREAD

**Issue by zcattacz** [peterhinch/micropython-mqtt#112]
On connection recovery, I got the following error if last_will is not specified in config. 
This does not affect initial connect().

```
Connecting to broker.
Task exception wasn't retrieved
future: <Task> coro= <generator object '_keep_connected' at 3ffea7e0>
Traceback (most recent call last):
  File "uasyncio/core.py", line 1, in run_until_complete
  File "mqtt_as.py", line 747, in _keep_connected
  File "mqtt_as.py", line 637, in connect
  File "mqtt_as.py", line 284, in _connect
TypeError: object of type 'int' has no len()
```

**Comment by peterhinch** [comment]
Please could you try the demo `clean.py`. This does not set the last will and has been extensively tested.

**Comment by zcattacz** [comment]
Can't replicate this right now :-(. whether clean.py or my script. Close for now.
