### ISSUE TITLE
config['gateway'] not defined - on Pi Pico W

### ISSUE THREAD

**Issue by gmrza** [peterhinch/micropython-mqtt#117]
After pulling the latest version this morning, I discovered a problem that config['gateway'] is not set.  I am running on a Pi Pico W, and get the following error when starting up:

Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "mqtt_flowserv01.py", line 533, in <module>
  File "mqtt_as.py", line 551, in __init__
  File "mqtt_as.py", line 171, in __init__
KeyError: gateway

adding the  following line to my code works around the problem:
`config['gateway'] = None

**Comment by ebolisa** [comment]
Could you show line 3? And what’s mqtt_flowserv01.py? Could the error be related to the changes you made?

**Comment by peterhinch** [comment]
Apologies, this is now fixed.
