### ISSUE TITLE
Issue with the memoryview

### ISSUE THREAD

**Issue by Valadimirovich** [peterhinch/micropython-mqtt#135]
I am not sure if it's related to the use of 1.23 firmware, but it happens during the initial connection after the reset

Traceback (most recent call last):
  File "asyncio/core.py", line 1, in run_until_complete
  File "<stdin>", line 448, in outgoing
  File "mqtt_as.py", line 797, in publish
  File "mqtt_as.py", line 409, in publish
  File "mqtt_as.py", line 444, in _publish
  File "mqtt_as.py", line 235, in _as_write
TypeError: object with buffer protocol required

**Comment by peterhinch** [comment]
Please can you give me some more detail.
1. What hardware are you using?
2. Does the error occur if you run the `range.py` demo?

**Comment by Valadimirovich** [comment]
Thank you for your prompt response

1. ESP32-S3 with SPIRAM, n8r2
2. Nope, range.py runs fine

**Comment by peterhinch** [comment]
If `range.py` runs, publications are occurring successfully, which suggests that the firmware is OK.

The `topic` and `msg` args should be `bytes` or `bytearray` instances: the traceback suggests that something else is being passed.
